### ISSUE TITLE
Historical map overlay not displaying

### ISSUE THREAD

**Issue by brundin** [cwrc/CWRC-Mapping-Timelines-Project#29]
The historical map overlay feature is no longer displaying in the standalone development version at http://apps.testing.cwrc.ca/cwrc-mtp/  Was working at one time, but now it is not.

**Comment by robinetmiller** [comment]
This works for me on my copy. It takes an long time to load because the map file is huge (19mb). It might be possible to optimize by slicing it into chunks like a standard google map. There are some scripts that can accomplish this, and I can pursue it if requested (approx 1 day).

**Comment by brundin** [comment]
Right -- it didn't work for a while, but Hamman fixed it a while back.  Sorry -- I should have closed this issue after Hamman fixed it.

The PNG map image used to be a really huge 43.6 MB, but I used pngquant (a command line utility for lossy compression of PNG images) to reduce the size down to a relatively svelte 18.9 MB.  There is a bit of lag time still, but it is way less than it was, and the delay in loading is not too bad now.

So, no need to worry about this issue anymore.
